var searchData=
[
  ['s_20own_20overlay_0',['6. The Engine&apos;s Own Overlay',['../ui_system.html#autotoc_md231',1,'']]],
  ['safely_1',['9. Switch scenes safely',['../tutorial_small_game.html#autotoc_md216',1,'']]],
  ['scene_2',['Your First Scene',['../your_first_scene.html',1,'']]],
  ['scene_3',['scene',['../tutorial_small_game.html#autotoc_md208',1,'1. Declare the scene'],['../getting_started.html#autotoc_md99',1,'5. Write the scene']]],
  ['scene_20and_20switch_20to_20it_4',['Add a second scene and switch to it',['../your_first_scene.html#autotoc_md256',1,'']]],
  ['scenes_5',['1. Application, GameBase, and Scenes',['../scene_and_objects.html#autotoc_md168',1,'']]],
  ['scenes_20objects_20and_20components_6',['Scenes, Objects, and Components',['../scene_and_objects.html',1,'']]],
  ['scenes_20safely_7',['9. Switch scenes safely',['../tutorial_small_game.html#autotoc_md216',1,'']]],
  ['screen_20space_20and_20post_20processing_8',['Screen space and post processing',['../graphics_features.html#autotoc_md108',1,'']]],
  ['second_20scene_20and_20switch_20to_20it_9',['Add a second scene and switch to it',['../your_first_scene.html#autotoc_md256',1,'']]],
  ['see_20also_10',['See also',['../building_shipping.html#autotoc_md61',1,'See also'],['../performance_guide.html#autotoc_md141',1,'See also']]],
  ['semantics_11',['3. Dispatch Semantics',['../events_and_input.html#autotoc_md87',1,'']]],
  ['serialization_12',['7. Serialization',['../assets_resources.html#autotoc_md27',1,'']]],
  ['shader_13',['Shader',['../shader_authoring.html#autotoc_md178',1,'1. How a Path Becomes a Shader'],['../animation.html#autotoc_md9',1,'5. How Bone Matrices Reach the Shader']]],
  ['shader_20authoring_14',['Shader Authoring',['../shader_authoring.html',1,'']]],
  ['shader_20stems_15',['5. Custom Vertex Formats and Shader Stems',['../shader_authoring.html#autotoc_md186',1,'']]],
  ['shaders_16',['Shaders',['../building_shipping.html#autotoc_md55',1,'']]],
  ['shadow_20mapping_17',['5. Shadow Mapping',['../lighting.html#autotoc_md123',1,'']]],
  ['shadows_18',['Shadows',['../backend_support.html#autotoc_md35',1,'3. Shadows'],['../lighting.html',1,'Lighting and Shadows'],['../graphics_features.html#autotoc_md107',1,'Shadows']]],
  ['shared_20resource_20types_19',['4. Shared Resource Types',['../rendering_pipeline.html#autotoc_md162',1,'']]],
  ['shipping_20',['Building and Shipping',['../building_shipping.html',1,'']]],
  ['sibling_21',['Or check the engine out as a sibling',['../building_shipping.html#autotoc_md47',1,'']]],
  ['skeleton_22',['2. Skeleton',['../animation.html#autotoc_md3',1,'']]],
  ['sleak_3a_3aeventdispatcher_23',['1. Events (&lt;span class=&quot;tt&quot;&gt;Sleak::EventDispatcher&lt;/span&gt;)',['../events_and_input.html#autotoc_md83',1,'']]],
  ['sleak_3a_3aphysics_3a_3adynamicaabbtree_24',['2. Dynamic AABB Tree (&lt;span class=&quot;tt&quot;&gt;Sleak::Physics::DynamicAABBTree&lt;/span&gt;)',['../physics.html#autotoc_md145',1,'']]],
  ['sleak_3a_3aphysics_3a_3aphysicsworld_25',['1. Physics World (&lt;span class=&quot;tt&quot;&gt;Sleak::Physics::PhysicsWorld&lt;/span&gt;)',['../physics.html#autotoc_md143',1,'']]],
  ['sleak_3a_3arefptr_26',['3. Smart Pointers (&lt;span class=&quot;tt&quot;&gt;Sleak::RefPtr&lt;/span&gt;)',['../scene_and_objects.html#autotoc_md172',1,'']]],
  ['sleak_3a_3avertexlayoutdesc_27',['1. &lt;span class=&quot;tt&quot;&gt;Sleak::VertexLayoutDesc&lt;/span&gt;',['../vertex_format.html#autotoc_md235',1,'']]],
  ['sleakengine_28',['SleakEngine',['../index.html',1,'']]],
  ['small_20game_29',['Tutorial: A Small Game',['../tutorial_small_game.html',1,'']]],
  ['smart_20pointers_20sleak_3a_3arefptr_30',['3. Smart Pointers (&lt;span class=&quot;tt&quot;&gt;Sleak::RefPtr&lt;/span&gt;)',['../scene_and_objects.html#autotoc_md172',1,'']]],
  ['something_20animated_31',['1. Getting Something Animated',['../animation.html#autotoc_md1',1,'']]],
  ['something_20to_20collide_20with_32',['Give the world something to collide with',['../your_first_scene.html#autotoc_md249',1,'']]],
  ['something_20with_20input_33',['6. Move something with input',['../tutorial_small_game.html#autotoc_md213',1,'']]],
  ['source_34',['Source',['../culling.html#autotoc_md67',1,'3. Where to Look in the Source'],['../events_and_input.html#autotoc_md89',1,'4. Where to Look in the Source'],['../physics.html#autotoc_md151',1,'5. Where to Look in the Source'],['../scene_and_objects.html#autotoc_md176',1,'5. Where to Look in the Source'],['../vertex_format.html#autotoc_md243',1,'5. Where to Look in the Source'],['../rendering_pipeline.html#autotoc_md166',1,'6. Where to Look in the Source'],['../animation.html#autotoc_md13',1,'7. Where to Look in the Source'],['../backend_support.html#autotoc_md43',1,'7. Where to Look in the Source'],['../debug_tools.html#autotoc_md81',1,'7. Where to Look in the Source'],['../lighting.html#autotoc_md127',1,'7. Where to Look in the Source'],['../shader_authoring.html#autotoc_md190',1,'7. Where to Look in the Source'],['../troubleshooting.html#autotoc_md204',1,'7. Where to Look in the Source'],['../ui_system.html#autotoc_md233',1,'7. Where to Look in the Source'],['../assets_resources.html#autotoc_md29',1,'8. Where to Look in the Source']]],
  ['space_20and_20post_20processing_35',['Screen space and post processing',['../graphics_features.html#autotoc_md108',1,'']]],
  ['spatial_20partitioning_36',['Physics and Spatial Partitioning',['../physics.html',1,'']]],
  ['spawn_20the_20pickups_37',['5. Spawn the pickups',['../tutorial_small_game.html#autotoc_md212',1,'']]],
  ['spir_20v_38',['2. GLSL and SPIR-V',['../shader_authoring.html#autotoc_md180',1,'']]],
  ['split_20in_20detail_39',['5. The Deferred Split in Detail',['../rendering_pipeline.html#autotoc_md164',1,'']]],
  ['staging_40',['Asset staging',['../building_shipping.html#autotoc_md53',1,'']]],
  ['start_20from_20a_20preset_41',['Start from a preset',['../performance_guide.html#autotoc_md129',1,'']]],
  ['start_20from_20the_20template_42',['Start from the template',['../building_shipping.html#autotoc_md45',1,'']]],
  ['started_43',['Getting Started',['../getting_started.html',1,'']]],
  ['startup_20and_20assets_44',['1. Startup and Assets',['../troubleshooting.html#autotoc_md192',1,'']]],
  ['state_20machine_45',['4. The State Machine',['../animation.html#autotoc_md7',1,'']]],
  ['stems_46',['5. Custom Vertex Formats and Shader Stems',['../shader_authoring.html#autotoc_md186',1,'']]],
  ['support_47',['Support',['../rendering_pipeline.html#autotoc_md158',1,'2. Per-Backend Feature Support'],['../backend_support.html',1,'Backend Feature Support']]],
  ['switch_20scenes_20safely_48',['9. Switch scenes safely',['../tutorial_small_game.html#autotoc_md216',1,'']]],
  ['switch_20to_20it_49',['Add a second scene and switch to it',['../your_first_scene.html#autotoc_md256',1,'']]],
  ['sync_50',['6. Keeping Variants in Sync',['../shader_authoring.html#autotoc_md188',1,'']]],
  ['system_51',['UI System',['../ui_system.html',1,'']]],
  ['system_20metrics_52',['6. System Metrics',['../debug_tools.html#autotoc_md79',1,'']]]
];
